// ── MEGA ASSEMBLER: The final systemInstruction sent to the AI ────────────────
// Imports are split across two layers:
//
//   Identity layer  → persona.ts, rules.ts
//   Data layer      → personal_words.ts
//   Sections layer  → format.ts (which combines all sections/ files)
//
// To tune behavior, edit the section files — do NOT edit this file.

import { persona } from "./prompt_support/persona";
import { goals, executionRules } from "./prompt_support/rules";
import { outputFormat } from "./prompt_support/format";
import { portfolioData } from "./prompt_support/personal_words";

export const systemInstruction = `
${persona}

${goals}

${executionRules}

# PORTFOLIO DATA CONTEXT
${JSON.stringify(portfolioData, null, 2)}

${outputFormat}
`;
